/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.hoaDon;

import dao.ChiTietYeuCau_DAO;
import dao.HoaDon_DAO;
import entity.ChiTietYeuCau;
import entity.HoaDon;
import entity.MonAn;
import entity.YeuCauKhachHang;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Frame_HoaDon extends javax.swing.JFrame {
    private HoaDon hoaDon;
    private HoaDon_DAO hoaDonDAO;
    private String maHD;
    
    private YeuCauKhachHang yeuCauKhachHang;
    private ChiTietYeuCau_DAO chiTietYeuCauDAO;
    private ChiTietYeuCau chiTietYeuCau;
    private DefaultTableModel tableModel;
    
    LocalDate ngayDat;
    LocalDate ngayNhan;
    /**
     * Creates new form Frame_HoaDon1
     */
    public Frame_HoaDon(String maHD) {
        try {
            initComponents();
            
            chiTietYeuCauDAO = new ChiTietYeuCau_DAO();
            hoaDonDAO = new HoaDon_DAO();
            this.hoaDon = hoaDonDAO.getHoaDonByMaHD(maHD);
            this.maHD = maHD;
            
            setSize(1000, 830);
            setLocationRelativeTo(null);
            
            t_maHoaDon.setText(maHD);
            t_maBan.setText(hoaDon.getBan().getMaBan());
            
            lb_tenNV.setText(hoaDon.getNhanVien().getTenNV());
            lb_tenKH.setText(hoaDon.getYeucau().getKh().getTenKH());
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            ngayDat = hoaDon.getThoiGianTao();
            ngayNhan = hoaDon.getNgayDatBan();
            t_ngayDat.setText(dtf.format(ngayDat));
            t_ngayNhan.setText(dtf.format(ngayNhan));
            
            table_thongtinMon.setFont(new Font("Arial", Font.PLAIN, 16));
            table_thongtinMon.getTableHeader().setFont(new Font("Arial", Font.BOLD, 16));
            table_thongtinMon.setRowHeight(30);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
            table_thongtinMon.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            table_thongtinMon.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            table_thongtinMon.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
            table_thongtinMon.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
            
            loadThongTinMonAn();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadThongTinMonAn() {
        
        DecimalFormat df = new DecimalFormat("#,### VNĐ  ");
        DecimalFormat df0 = new DecimalFormat("#,###");
        yeuCauKhachHang = hoaDon.getYeucau();
        List<ChiTietYeuCau> dsYeuCau = chiTietYeuCauDAO.getChiTietYeuCauByMaYeuCau(yeuCauKhachHang.getMaYeuCau());
        
        tableModel = (DefaultTableModel) table_thongtinMon.getModel();
        // Clear bảng trước khi load dữ liệu mới
        tableModel.setRowCount(0);
        // Duyệt qua danh sách món ăn và thêm vào bảng
        int stt = 1;
        double tongTien = 0;
        for (ChiTietYeuCau yeuCau : dsYeuCau) {
            MonAn monAn = yeuCau.getMonAn();
            tongTien += yeuCau.getSoLuong() * monAn.getGiaTien();
            tableModel.addRow(new Object[]{
                stt++,
                monAn.getTenMonAn(),
                yeuCau.getSoLuong(),
                df0.format(monAn.getGiaTien()),
                df0.format(yeuCau.getSoLuong() * monAn.getGiaTien())
            });
        }
        lb_tongTienMonAn.setText(df0.format(tongTien));
        lb_tienThue.setText(df0.format(tongTien*0.1));
        lb_tongTien.setText(df.format(tongTien + tongTien*0.1));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lb_tenNV = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lb_tenKH = new javax.swing.JLabel();
        P_ttHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_maHoaDon = new javax.swing.JLabel();
        t_maBan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_thongtinMon = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btn_xuatHoaDon = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lb_tienThue = new javax.swing.JLabel();
        lb_tongTienMonAn = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        P_ttHoaDon1 = new javax.swing.JPanel();
        t_ngayDat = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t_ngayNhan = new javax.swing.JLabel();
        lb_tongTien = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("HÓA ĐƠN BÁN HÀNG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tên Nhân Viên:");

        lb_tenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tenNV.setText("asdasd");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Tên khách hàng:");

        lb_tenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tenKH.setText("asdasdas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_tenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(lb_tenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_ttHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mã hóa đơn:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Bàn:");

        t_maHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_maHoaDon.setText("asdasd");

        t_maBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_maBan.setText("asdasda");

        javax.swing.GroupLayout P_ttHoaDonLayout = new javax.swing.GroupLayout(P_ttHoaDon);
        P_ttHoaDon.setLayout(P_ttHoaDonLayout);
        P_ttHoaDonLayout.setHorizontalGroup(
            P_ttHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ttHoaDonLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(P_ttHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P_ttHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_maBan, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P_ttHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_maHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12))
        );
        P_ttHoaDonLayout.setVerticalGroup(
            P_ttHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ttHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_ttHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_maHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P_ttHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ttHoaDonLayout.createSequentialGroup()
                        .addGroup(P_ttHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_maBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_thongtinMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên món ăn", "S.L", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_thongtinMon);
        if (table_thongtinMon.getColumnModel().getColumnCount() > 0) {
            table_thongtinMon.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Danh sách món ăn: ");

        btn_xuatHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        btn_xuatHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/invoice (4) (1).png"))); // NOI18N
        btn_xuatHoaDon.setText("In hóa đơn");
        btn_xuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatHoaDonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Tiền thuế VAT: ");

        lb_tienThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tienThue.setForeground(new java.awt.Color(0, 102, 102));
        lb_tienThue.setText("sadasd");

        lb_tongTienMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tongTienMonAn.setForeground(new java.awt.Color(0, 102, 102));
        lb_tongTienMonAn.setText("sadasd");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Tổng tiền món ăn: ");

        P_ttHoaDon1.setBackground(new java.awt.Color(255, 255, 255));

        t_ngayDat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_ngayDat.setText("sdawdawd");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Ngày lập hóa đơn:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Ngày nhận bàn:");

        t_ngayNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_ngayNhan.setText("asdadwda");

        javax.swing.GroupLayout P_ttHoaDon1Layout = new javax.swing.GroupLayout(P_ttHoaDon1);
        P_ttHoaDon1.setLayout(P_ttHoaDon1Layout);
        P_ttHoaDon1Layout.setHorizontalGroup(
            P_ttHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ttHoaDon1Layout.createSequentialGroup()
                .addGroup(P_ttHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ttHoaDon1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_ngayDat, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(P_ttHoaDon1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_ngayNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        P_ttHoaDon1Layout.setVerticalGroup(
            P_ttHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ttHoaDon1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_ttHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_ngayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_ttHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_ngayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lb_tongTien.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lb_tongTien.setForeground(new java.awt.Color(0, 102, 102));
        lb_tongTien.setText("sadasd");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel16.setText("Tổng tiền thanh toán: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_tongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_tienThue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_tongTienMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_xuatHoaDon)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(P_ttHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(P_ttHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(P_ttHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(P_ttHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tongTienMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_tienThue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_xuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatHoaDonActionPerformed
        HoaDon hoaDon = hoaDonDAO.getHoaDonByMaHD(maHD); // Lấy thông tin hóa đơn
        if (hoaDon == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Lấy danh sách chi tiết yêu cầu từ mã yêu cầu trong hóa đơn
        List<ChiTietYeuCau> dsChiTietYeuCau = chiTietYeuCauDAO.getChiTietYeuCauByMaYeuCau(hoaDon.getYeucau().getMaYeuCau());

        String relativePath = "resources/hoaDon/HoaDon_" + maHD + ".pdf";

        // Lấy đường dẫn đầy đủ (tương đối từ thư mục gốc của dự án)
        File file = new File(relativePath);

        // Kiểm tra và tạo thư mục nếu chưa tồn tại
        File directory = file.getParentFile();
        if (!directory.exists()) {
            directory.mkdirs();
        }

        // Xuất hóa đơn ra PDF
        hoaDonDAO.exportHoaDonToPDF(hoaDon, dsChiTietYeuCau, file.getAbsolutePath());
//        PDFViewer pdfview = new PDFViewer(file.getAbsolutePath());
        this.dispose();
        if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (file.exists()) {
                    try {
                        desktop.open(new File(file.getAbsolutePath())); // Mở file PDF
                    } catch (IOException ex) {
                        Logger.getLogger(Frame_HoaDon.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    System.out.println("File không tồn tại.");
                }
            }
    }//GEN-LAST:event_btn_xuatHoaDonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_ttHoaDon;
    private javax.swing.JPanel P_ttHoaDon1;
    private javax.swing.JButton btn_xuatHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_tenKH;
    private javax.swing.JLabel lb_tenNV;
    private javax.swing.JLabel lb_tienThue;
    private javax.swing.JLabel lb_tongTien;
    private javax.swing.JLabel lb_tongTienMonAn;
    private javax.swing.JLabel t_maBan;
    private javax.swing.JLabel t_maHoaDon;
    private javax.swing.JLabel t_ngayDat;
    private javax.swing.JLabel t_ngayNhan;
    private javax.swing.JTable table_thongtinMon;
    // End of variables declaration//GEN-END:variables
}
