/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.hoaDon.huongDanSuDung;

import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author Admin
 */
public class PDF_HuongDanSuDung extends javax.swing.JPanel {

    /**
     * Creates new form PDF_HuongDanSuDUng
     */
    public PDF_HuongDanSuDung(String pdfFilePath) {
        initComponents();

        try {
            // Load PDF document
            PDDocument document = PDDocument.load(new File(pdfFilePath));
            PDFRenderer renderer = new PDFRenderer(document);

            // Panel chứa các trang PDF
            JPanel pdfPanel = new JPanel();
            pdfPanel.setLayout(new BoxLayout(pdfPanel, BoxLayout.Y_AXIS));

            // Render từng trang và thêm vào panel
            for (int i = 0; i < document.getNumberOfPages(); i++) {
                BufferedImage image = renderer.renderImageWithDPI(i, 150); // Render mỗi trang ở 150 DPI
                JLabel label = new JLabel(new ImageIcon(image));

                // Panel chứa từng trang
                JPanel pagePanel = new JPanel();
                pagePanel.setLayout(new BorderLayout());
                pagePanel.add(label, BorderLayout.CENTER);

                // Thêm trang vào pdfPanel
                pdfPanel.add(pagePanel);
            }

            // Cuộn nếu PDF có nhiều trang
            JScrollPane scrollPane = new JScrollPane(pdfPanel);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

            // Thêm JScrollPane vào container của giao diện
            P_pdf.setLayout(new BorderLayout());
            P_pdf.add(scrollPane, BorderLayout.CENTER);

            // Đóng tài liệu PDF
            document.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(P_pdf, "Error loading PDF: " + ex.getMessage());
        }

        // Cập nhật giao diện
        P_pdf.validate();
        P_pdf.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_pdf = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout P_pdfLayout = new javax.swing.GroupLayout(P_pdf);
        P_pdf.setLayout(P_pdfLayout);
        P_pdfLayout.setHorizontalGroup(
            P_pdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        P_pdfLayout.setVerticalGroup(
            P_pdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_pdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_pdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_pdf;
    // End of variables declaration//GEN-END:variables
}
