/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.KhachHangNhanVien;

import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Frame_XemThongTinNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form Frame_XemThonTinNhanVien
     */
    public Frame_XemThongTinNhanVien(String maNV) {
        initComponents();
        JPanel panel_tt = new JPanel();
        
        Panel_chinh.removeAll();
        Panel_chinh.setLayout(new java.awt.BorderLayout());
        Panel_chinh.add(panel_tt);
        Panel_chinh.validate();
        Panel_chinh.repaint();
        
        XemThongTinNhanVien xtt = new XemThongTinNhanVien(maNV);
        panel_tt.add(xtt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_chinh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_chinh.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel_chinhLayout = new javax.swing.GroupLayout(Panel_chinh);
        Panel_chinh.setLayout(Panel_chinhLayout);
        Panel_chinhLayout.setHorizontalGroup(
            Panel_chinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        Panel_chinhLayout.setVerticalGroup(
            Panel_chinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_chinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_chinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_chinh;
    // End of variables declaration//GEN-END:variables
}
